{
  $FF  $FF  $00  $FF  $FF  $FF  $FF  $00  
  $FF  $00  $FF  $00  $FF  $00  $FF  $00  
  $FF  $00  $FF  $00  $FF  $00  $FF  $00  
  $FF  $00  $FF  $FF  $00  $FF  $FF  $FF  
  $FF  $00  $FF  $00  $FF  $00  $FF  $00  
  $FF  $00  $FF  $00  $FF  $00  $FF  $00  
  $FF  $FF  $FF  $FF  $FF  $FF  $00  $FF  
  $FF  $00  $FF  $00  $FF  $00  $FF  $00  
  $EF  $1F  $EF  $1F  $EF  $1F  $EF  $1F  
  $EF  $1F  $EF  $1F  $EF  $1F  $EF  $1F  
  $EF  $1F  $EF  $1F  $EF  $1F  $E0  $1F  
  $FF  $00  $FF  $00  $FF  $00  $FF  $00  
  $FF  $FF  $FF  $FF  $FF  $FF  $0F  $FF  
  $EF  $1F  $EF  $1F  $EF  $1F  $EF  $1F  
  $DF  $3F  $DF  $3F  $DF  $3F  $C0  $3F  
  $FF  $00  $FF  $00  $FF  $00  $FF  $00 
}